const API=location.protocol==="file:"?"http://localhost:8000/api":(location.protocol+"//"+location.host)+"/api";
function token(){return localStorage.getItem("token")||localStorage.getItem("lm_token")||""}
function currentUser(){try{return JSON.parse(localStorage.getItem("lm_user")||"null")}catch{return null}}
function logout(){localStorage.removeItem("lm_token");localStorage.removeItem("lm_user");location.href="login.html"}
function showAuthError(message){const banner=document.getElementById("auth-alert")||document.getElementById("message");if(banner){banner.textContent=message;banner.style.display="block";banner.style.color="#b42318";banner.style.background="#fff1f0";banner.style.padding="10px 12px";banner.style.borderRadius="6px"}}
async function api(path,opts={}){opts.headers=opts.headers||{};if(token())opts.headers.Authorization="Bearer "+token();if(opts.body&&typeof opts.body==="object"&&!(opts.body instanceof FormData)){opts.headers["Content-Type"]="application/json";opts.body=JSON.stringify(opts.body)};let r;try{r=await fetch(API+path,opts)}catch(e){e.network=true;throw e}if(!r.ok){let body={};try{body=await r.json()}catch{};const e=new Error(body.detail||`Request failed (${r.status})`);e.status=r.status;if(r.status===401)showAuthError("Authentication failed. Please sign in again; your session may be expired or your password may be incorrect.");throw e}return r.headers.get("content-type")?.includes("application/json")?r.json():r}
const QUEUE_KEY="lm_inspection_queue";
const QUEUE_DB="lm_offline_queue";
function inspectionQueue(){try{return JSON.parse(localStorage.getItem(QUEUE_KEY)||"[]")}catch{return[]}}
function mirrorQueueToIndexedDb(items){if(!window.indexedDB)return;const request=indexedDB.open(QUEUE_DB,1);request.onupgradeneeded=()=>request.result.createObjectStore("inspections",{keyPath:"local_id"});request.onsuccess=()=>{const tx=request.result.transaction("inspections","readwrite"),store=tx.objectStore("inspections");store.clear();items.forEach(item=>store.put(item))}}
function hydrateQueueFromIndexedDb(){return new Promise(resolve=>{if(!window.indexedDB)return resolve();const request=indexedDB.open(QUEUE_DB,1);request.onupgradeneeded=()=>request.result.createObjectStore("inspections",{keyPath:"local_id"});request.onsuccess=()=>{const tx=request.result.transaction("inspections","readonly"),get=tx.objectStore("inspections").getAll();get.onsuccess=()=>{if(get.result.length)localStorage.setItem(QUEUE_KEY,JSON.stringify(get.result));resolve()};get.onerror=()=>resolve()};request.onerror=()=>resolve()})}
function setInspectionQueue(items){localStorage.setItem(QUEUE_KEY,JSON.stringify(items));mirrorQueueToIndexedDb(items);updateConnectionStatus()}
function updateConnectionStatus(message){let el=document.getElementById("connection-status");if(!el){el=document.createElement("div");el.id="connection-status";el.style="position:fixed;right:16px;bottom:16px;z-index:100;color:white;padding:10px 14px;border-radius:6px;font:600 13px sans-serif;background:#15803d;box-shadow:0 4px 16px #0003";document.body.appendChild(el)};const online=!window.lmSandboxOffline&&navigator.onLine;const queued=inspectionQueue().length;el.textContent=message||(`${online?"Online":"Offline"}${queued?` - ${queued} inspection${queued===1?"":"s"} queued`:""}`);el.style.background=online?"#15803d":"#b45309"}
async function syncInspectionQueue(){if(!navigator.onLine||!token())return;const records=inspectionQueue();if(!records.length){updateConnectionStatus();return}try{const result=await api("/inspections/sync-batch",{method:"POST",body:{records}});const rejected=new Set((result.rejected||[]).map(x=>x.local_id));setInspectionQueue(records.filter(x=>rejected.has(x.local_id)));updateConnectionStatus(result.rejected?.length?`${result.synced_count} synced; ${result.rejected.length} rejected by geo-fence`:"Offline inspections synced")}catch(e){updateConnectionStatus("Reconnect pending")}}
function browserPosition(){return new Promise((resolve,reject)=>{const active=window.demoGeoOverride||window.lmSandboxGps; if(active)return resolve({latitude:active.latitude,longitude:active.longitude});if(!navigator.geolocation)return reject(new Error("Location services are unavailable"));navigator.geolocation.getCurrentPosition(p=>resolve({latitude:p.coords.latitude,longitude:p.coords.longitude}),()=>reject(new Error("Location permission is required for inspection submission")),{enableHighAccuracy:true,timeout:10000,maximumAge:0})})}
function applyDemoGeo(latitude, longitude, label) {
  const lat = Number(latitude);
  const lon = Number(longitude);
  if (!Number.isFinite(lat) || !Number.isFinite(lon)) {
    alert("Enter valid numeric latitude and longitude values.");
    return null;
  }
  const point = { latitude: lat, longitude: lon };
  window.lmSandboxGps = point;
  window.demoGeoOverride = point;
  const latField = document.getElementById("lat-input");
  const lonField = document.getElementById("lon-input");
  if (latField) latField.value = String(lat);
  if (lonField) lonField.value = String(lon);
  const geoStatus = document.getElementById("geo-status");
  if (geoStatus) geoStatus.textContent = label || "Demo GPS";
  updateConnectionStatus(label ? `Demo GPS: ${label}` : "Demo GPS active");
  return point;
}
function showApiError(e){if(e.status===400)alert("The QR signature is invalid or tampered.");else if(e.status===422)alert(e.message||"The inspector is outside the permitted 200-meter geofence.");else if(e.network)alert("Network unavailable. The inspection will remain queued until reconnect.");else alert(e.message||"Request failed")}
async function issueDigitalCertificate(){
 try{
  let applicationId=window.currentApplicationId;
  if(!applicationId){const pending=await api("/v1/applications/pending");applicationId=pending[0]?.application_id;window.currentApplicationId=applicationId}
  if(!applicationId)return showAuthError("No pending application is available for certificate issuance.");
  const issued=await api("/v1/certificates/issue",{method:"POST",body:{application_id:applicationId}});
  const base=location.protocol==="file:"?"http://localhost:8000":location.origin;
  const modal=document.createElement("div");modal.style="position:fixed;inset:0;z-index:160;background:#001428cc;display:grid;place-items:center;padding:20px";modal.innerHTML=`<div style="width:min(430px,100%);background:#fff;border-radius:10px;padding:24px;text-align:center;font-family:Public Sans,sans-serif"><div style="display:inline-block;padding:8px 12px;border-radius:999px;background:#dcfce7;color:#15803d;font-weight:700">Digital Certificate Successfully Signed and Issued</div><h2 style="color:#001428;margin:16px 0 6px">${issued.certificate_id}</h2><img alt="Certificate verification QR code" src="data:image/png;base64,${issued.qr_base64}" style="width:220px;height:220px;image-rendering:auto;margin:8px auto;display:block"><div style="display:flex;gap:8px;justify-content:center;flex-wrap:wrap"><a href="${base}${issued.pdf_download_url}" target="_blank" rel="noopener" style="padding:10px 12px;border-radius:5px;background:#0f2942;color:#fff;text-decoration:none;font-weight:700">Download PDF Certificate</a><a href="${issued.verification_url}" target="_blank" rel="noopener" style="padding:10px 12px;border-radius:5px;background:#fd651e;color:#fff;text-decoration:none;font-weight:700">Test Public Verification</a></div><button id="close-issued-certificate" type="button" style="margin-top:16px;padding:8px 14px;border:1px solid #c3c6ce;background:#fff;border-radius:5px;color:#314863">Close</button></div>`;document.body.appendChild(modal);document.getElementById("close-issued-certificate").onclick=()=>modal.remove();
 }catch(error){showApiError(error)}
}
function go(p){location.href=p}
async function handleApiLoginSubmit(event){event.preventDefault();const email=document.getElementById("modal-username")?.value.trim();const password=document.getElementById("modal-password")?.value;if(!email||!password)return showAuthError("Enter both email and password.");try{const d=await api("/v1/auth/login",{method:"POST",body:{email,password}});localStorage.setItem("token",d.access_token);localStorage.setItem("lm_token",d.access_token);localStorage.setItem("lm_user",JSON.stringify(d.user));if(typeof closeLoginModal==="function")closeLoginModal();const p=d.user.role==="TRADER"?"merchant.html":d.user.role==="ADMIN"?"admin.html":"lmo.html";go(p)}catch(e){showAuthError(e.status===401?"Authentication failed. Check the email and password, then try again.":e.message)}}
async function handleCertificateSearch(event){event?.preventDefault();const n=document.getElementById("cert-number-input")?.value.trim();if(!n)return;try{const d=await api("/certificates/verify?number="+encodeURIComponent(n));const box=document.getElementById("cert-result-box"),title=document.getElementById("res-cert-title");if(title)title.textContent=`Digital Stamping Certificate #${d.certificate_number}`;if(box)box.classList.remove("hidden");window.lastCertificate=d}catch(e){alert(e.message)}}
async function executeVerificationAudit(){const q=document.getElementById("query-input")?.value.trim();if(!q)return;try{const d=await api("/certificates/verify?number="+encodeURIComponent(q));window.lastCertificate=d;const result=document.getElementById("verification-result")||document.getElementById("result-panel");if(result){result.classList.remove("hidden");result.scrollIntoView({behavior:"smooth"})}else alert(`Verified: ${d.certificate_number} | ${d.status}`)}catch(e){alert(e.message)}}
async function downloadOfficialPdf(){if(!window.lastCertificate)return alert("Audit a valid certificate first.");try{const pdf=await api("/certificates/"+window.lastCertificate.id+"/pdf");const url=URL.createObjectURL(await pdf.blob());const modal=document.createElement("div");modal.style="position:fixed;inset:0;background:#001428dd;z-index:90;padding:5vh 5vw";modal.innerHTML=`<div style="height:90%;background:white;position:relative"><button style="position:absolute;right:8px;top:8px;z-index:1" aria-label="Close PDF viewer">Close</button><iframe title="Certificate PDF" src="${url}" style="width:100%;height:100%;border:0"></iframe></div>`;modal.querySelector("button").onclick=()=>{URL.revokeObjectURL(url);modal.remove()};document.body.appendChild(modal)}catch(e){showApiError(e)}}
async function submitTamperNotice(){const modal=document.getElementById("report-modal");const ta=modal?.querySelector("textarea");try{const d=await api("/tamper-reports",{method:"POST",body:{query_value:document.getElementById("query-input")?.value||"UNKNOWN",reason:ta?.value||"Suspected tampering"}});alert("Statutory Incident Report Dispatched. Incident reference: "+d.reference);closeTamperingModal?.()}catch(e){alert(e.message)}}
async function sendAdvisorySuccess(){try{const title=document.querySelector("#advisoryModal input")?.value||"Gazette Bulletin";const message=document.querySelector("#advisoryModal textarea")?.value||"Regulatory advisory dispatched.";await api("/admin/advisories",{method:"POST",body:{title,message}});toggleAdvisoryModal();showToast("Gazette Bulletin Dispatched","Advisory stored and broadcast workflow completed.","campaign")}catch(e){alert(e.message)}}
document.addEventListener("DOMContentLoaded",async()=>{
 document.querySelectorAll('a[href="#"]').forEach(a=>{const t=a.textContent.trim();if(t.includes("User Dashboard"))a.href="merchant.html";else if(t.includes("LMO Portal"))a.href="lmo.html";else if(t.includes("Admin Console"))a.href="admin.html";else if(t.includes("Verify Certificate"))a.href="verify.html";else if(t.includes("Back to Public Portal"))a.href="index.html"});
 const page=location.pathname.split("/").pop();
 if(page==="merchant.html"){try{const [ins,apps]=await Promise.all([api("/instruments"),api("/applications")]);window.lmData={ins,apps};console.log("Merchant data",window.lmData)}catch(e){console.warn(e.message)}}
 if(page==="admin.html"){try{const s=await api("/admin/stats");console.log("Admin stats",s)}catch(e){console.warn("Login required for live admin stats")}}
});

function showTraderToast(message){let toast=document.getElementById("trader-toast");if(!toast){toast=document.createElement("div");toast.id="trader-toast";toast.style="position:fixed;right:22px;top:22px;z-index:140;background:#15803d;color:white;padding:13px 16px;border-radius:7px;box-shadow:0 8px 24px #00142833;font:600 14px Public Sans,sans-serif";document.body.appendChild(toast)}toast.textContent=message;toast.hidden=false;clearTimeout(window.traderToastTimer);window.traderToastTimer=setTimeout(()=>{toast.hidden=true},6000)}
function updateTraderPendingCount(){const label=[...document.querySelectorAll("span")].find(element=>element.textContent.trim()==="Pending Applications");const count=label?.parentElement?.querySelector(".font-headline-lg");if(count)count.textContent=String(Number(count.textContent.trim())+1)}
function closeVerificationModal(){document.getElementById("new-verification-modal")?.remove()}
function createDemoApplication(){
 if(document.getElementById("new-verification-modal"))return;
 const modal=document.createElement("div");modal.id="new-verification-modal";modal.style="position:fixed;inset:0;z-index:130;background:#001428aa;display:grid;place-items:center;padding:20px";
 modal.innerHTML='<form id="new-verification-form" style="width:min(560px,100%);background:#fff;border-radius:10px;padding:24px;box-shadow:0 20px 60px #00142855;font-family:Public Sans,sans-serif"><div style="display:flex;justify-content:space-between;align-items:center"><div><div style="font-size:11px;letter-spacing:.1em;text-transform:uppercase;color:#74777e;font-weight:700">Trader workflow</div><h2 style="margin:4px 0 18px;color:#001428;font-size:24px">New Verification Application</h2></div><button id="close-verification-modal" type="button" aria-label="Close" style="border:0;background:transparent;color:#596b7e;font-size:22px;cursor:pointer">&times;</button></div><label style="display:block;margin:10px 0 5px;color:#314863;font-size:13px;font-weight:700">Instrument Category<input name="instrument_type" required value="Weighing Scale / Counter Scale" style="display:block;width:100%;box-sizing:border-box;margin-top:5px;padding:10px;border:1px solid #c3c6ce;border-radius:5px"></label><label style="display:block;margin:10px 0 5px;color:#314863;font-size:13px;font-weight:700">Serial Number<input name="serial_number" required placeholder="WM-2026-X91" style="display:block;width:100%;box-sizing:border-box;margin-top:5px;padding:10px;border:1px solid #c3c6ce;border-radius:5px"></label><label style="display:block;margin:10px 0 5px;color:#314863;font-size:13px;font-weight:700">Max Capacity (kg)<input name="capacity_kg" required type="number" min="0.1" step="0.1" value="50" style="display:block;width:100%;box-sizing:border-box;margin-top:5px;padding:10px;border:1px solid #c3c6ce;border-radius:5px"></label><label style="display:block;margin:10px 0 5px;color:#314863;font-size:13px;font-weight:700">Trade Category<input name="trade_category" required value="Retail" style="display:block;width:100%;box-sizing:border-box;margin-top:5px;padding:10px;border:1px solid #c3c6ce;border-radius:5px"></label><label style="display:block;margin:10px 0 5px;color:#314863;font-size:13px;font-weight:700">Location / Premises Address<input name="premises_address" required value="District Central, Zone 04" style="display:block;width:100%;box-sizing:border-box;margin-top:5px;padding:10px;border:1px solid #c3c6ce;border-radius:5px"></label><div id="verification-form-error" style="display:none;margin-top:12px;padding:10px;background:#fff1f0;color:#b42318;border-radius:5px;font-size:13px"></div><button type="submit" style="margin-top:18px;width:100%;padding:11px;border:0;border-radius:5px;background:#fd651e;color:#fff;font-weight:700;cursor:pointer">Submit Application</button></form>';
 document.body.appendChild(modal);document.getElementById("close-verification-modal").onclick=closeVerificationModal;modal.onclick=event=>{if(event.target===modal)closeVerificationModal()};
 document.getElementById("new-verification-form").onsubmit=async event=>{event.preventDefault();const form=new FormData(event.currentTarget);const error=document.getElementById("verification-form-error");try{const result=await api("/applications/create",{method:"POST",body:{instrument_type:form.get("instrument_type"),serial_number:form.get("serial_number"),capacity_kg:Number(form.get("capacity_kg")),trade_category:form.get("trade_category"),premises_address:form.get("premises_address")}});closeVerificationModal();updateTraderPendingCount();showTraderToast(`Application Submitted Successfully! ID: #${result.id.replace(/^LMO-APP-/,"")}`);const current=window.lmData?.apps||[];current.unshift(result);window.lmData={...(window.lmData||{}),apps:current};}catch(errorValue){error.textContent=errorValue.message||"Unable to submit application";error.style.display="block"}};
}
async function processFirstInspection(result){try{const inspectionUser=currentUser();const apps=await api(inspectionUser?.role==="TRADER"?"/applications":"/v1/lmo/applications");const a=apps.find(x=>["SCHEDULED","PAYMENT_PENDING","SUBMITTED"].includes(x.status));if(!a)return alert("No pending application found.");const position=await browserPosition();const record={local_id:crypto.randomUUID(),application_id:a.id,result,latitude:position.latitude,longitude:position.longitude,remarks:result==="PASS"?"Instrument passed field verification.":"Instrument failed verification.",readings:{schedule_checks:"8/8"}};if(!navigator.onLine){setInspectionQueue([...inspectionQueue(),record]);return alert("Inspection saved offline and queued for synchronization")}try{await api(inspectionUser?.role==="TRADER"?"/inspections":"/v1/lmo/inspections",{method:"POST",body:record})}catch(e){if(e.network){setInspectionQueue([...inspectionQueue(),record]);return alert("Network unavailable. Inspection queued for synchronization")}throw e}if(result==="PASS"){const c=await api("/certificates/"+a.id+"/generate",{method:"POST"});alert("Certificate issued: "+c.certificate_number)}else alert("Application rejected and inspection recorded.")}catch(e){showApiError(e)}}
async function adminAllot(){try{const apps=await api("/applications");const a=apps.find(x=>["SUBMITTED","PAYMENT_PENDING"].includes(x.status));if(!a)return alert("No pending applications.");const d=await api("/applications/"+a.id+"/schedule",{method:"POST"});alert("Application scheduled for "+new Date(d.scheduled_date).toLocaleString())}catch(e){alert(e.message)}}
document.addEventListener("DOMContentLoaded",()=>{
 updateConnectionStatus();hydrateQueueFromIndexedDb().then(syncInspectionQueue);
 document.querySelectorAll("button").forEach(b=>{const t=b.textContent.replace(/\s+/g," ").trim();
  if(/New Verification|Apply for Re-verification|Start New Verification/.test(t))b.addEventListener("click",createDemoApplication);
  if(/Sign & Issue Digital Certificate/.test(t))b.addEventListener("click",()=>location.pathname.endsWith("/lmo.html")?issueDigitalCertificate():processFirstInspection("PASS"));
  if(/Auto-Allot Eligible/.test(t))b.addEventListener("click",adminAllot);
 });
});
window.addEventListener("online",()=>{updateConnectionStatus("Connection restored");syncInspectionQueue()});
window.addEventListener("offline",()=>updateConnectionStatus("Offline - inspections will be queued"));

async function verifyQrToken(token){try{const d=await api("/certificates/verify-token?token="+encodeURIComponent(token));window.lastCertificate=d;const input=document.getElementById("query-input");if(input)input.value=token;alert(`Authentic certificate token for instrument ${d.instrument_serial}`);return d}catch(e){showApiError(e)}}
function extractQrToken(value){try{const url=new URL(value);const match=url.pathname.match(/\/certificates\/verify\/(.+)$/);return match?decodeURIComponent(match[1]):value}catch{return value}}
async function triggerQrScan(){const input=prompt("Paste the certificate QR token or verification URL");if(input)await verifyQrToken(extractQrToken(input.trim()))}
async function triggerQrScanModal(){
 if(!("BarcodeDetector" in window)||!navigator.mediaDevices?.getUserMedia){return triggerQrScan()}
 const modal=document.createElement("div");modal.style="position:fixed;inset:0;background:#001428ee;z-index:100;display:grid;place-items:center;padding:24px";
 modal.innerHTML='<div style="background:white;padding:16px;max-width:460px;width:100%;border-radius:8px"><video autoplay playsinline style="width:100%;background:#001428;border-radius:6px"></video><button type="button" style="margin-top:12px;padding:8px 12px">Cancel</button></div>';
 document.body.appendChild(modal);const video=modal.querySelector("video");let stream;
 const close=()=>{stream?.getTracks().forEach(track=>track.stop());modal.remove()};modal.querySelector("button").onclick=close;
 try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"environment"}});video.srcObject=stream;const detector=new BarcodeDetector({formats:["qr_code"]});
  const scan=async()=>{if(!document.body.contains(modal))return;try{const codes=await detector.detect(video);if(codes[0]?.rawValue){close();await verifyQrToken(extractQrToken(codes[0].rawValue));return}}catch{}requestAnimationFrame(scan)};scan();
 }catch{close();triggerQrScan()}
}

document.addEventListener("DOMContentLoaded",()=>{
 const locationButton=[...document.querySelectorAll("button")].find(button=>button.textContent.includes("Capture Field Coordinates"));
 if(locationButton)locationButton.addEventListener("click",async()=>{try{const position=await browserPosition();locationButton.textContent=`Coordinates captured: ${position.latitude.toFixed(5)}, ${position.longitude.toFixed(5)}`;locationButton.dataset.latitude=position.latitude;locationButton.dataset.longitude=position.longitude;updateConnectionStatus("GPS coordinates captured")}catch(e){showApiError(e)}});
});

function installSandboxNetworkSwitch(){
 if(window.__lmSandboxFetchInstalled)return;
 const nativeFetch=window.fetch.bind(window);
 window.fetch=(input,options)=>{
  const url=String(typeof input==="string"?input:input.url||"");
  if(window.lmSandboxOffline&&url.includes("/api/")&&!url.includes("/certificates/verify")){
   const error=new Error("Developer sandbox is simulating an offline connection");error.network=true;return Promise.reject(error);
  }
  return nativeFetch(input,options);
 };
 window.__lmSandboxFetchInstalled=true;
}
function setSandboxGps(latitude,longitude){
 window.lmSandboxGps={latitude,longitude};
 window.demoGeoOverride={latitude,longitude};
 try{navigator.geolocation.getCurrentPosition=(success)=>success({coords:{latitude,longitude,accuracy:1}})}catch{}
 const lat=document.getElementById("sandbox-lat"),lon=document.getElementById("sandbox-lon");if(lat)lat.textContent=latitude.toFixed(6);if(lon)lon.textContent=longitude.toFixed(6);updateConnectionStatus("Simulated GPS active")
}
async function loadSandboxTokens(){
 const select=document.getElementById("sandbox-token");if(!select||select.dataset.loaded)return;
 try{const data=await api("/v1/dev/sample-token");select.options[0].value=data.valid_token;select.options[1].value=data.tampered_token;select.dataset.loaded="true"}catch(e){select.options[0].textContent="Login/backend required for valid token"}
}
async function injectSandboxToken(){
 const tokenValue=document.getElementById("sandbox-token")?.value;if(!tokenValue)return alert("Choose a test token first.");
 const result=await verifyQrToken(tokenValue);if(result)document.getElementById("sandbox-result").textContent="Token accepted by the real verification endpoint.";
}
async function seedSandboxData(){
 try{const result=await api("/v1/dev/seed",{method:"POST"});document.getElementById("sandbox-result").textContent=`Seeded ${result.shops} shops, ${result.verified_scales} scales and ${result.officers} officers.`}catch(e){document.getElementById("sandbox-result").textContent=e.message}
}
function renderSandbox(){
 if(document.getElementById("dev-sandbox"))return;
 installSandboxNetworkSwitch();
 const style=document.createElement("style");style.textContent="#dev-sandbox{position:fixed;right:18px;bottom:58px;width:min(360px,calc(100vw - 36px));z-index:120;color:#e6edf3;background:#111827;border:1px solid #475569;border-radius:12px;box-shadow:0 18px 50px #0008;font:13px system-ui,sans-serif}#dev-sandbox header{display:flex;justify-content:space-between;align-items:center;padding:13px 15px;background:#1e293b;border-radius:12px 12px 0 0}#dev-sandbox section{padding:12px 15px;border-top:1px solid #334155}#dev-sandbox button,#dev-sandbox select,#dev-sandbox input{border:1px solid #64748b;background:#0f172a;color:#f8fafc;border-radius:6px;padding:7px 9px;cursor:pointer}#dev-sandbox button:hover{border-color:#38bdf8}#dev-sandbox .sandbox-grid{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:8px}#dev-sandbox .sandbox-inputs{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:8px}#dev-sandbox small{color:#94a3b8}#dev-sandbox .danger{border-color:#f87171}#dev-sandbox .demo-note{font-size:11px;color:#bfdbfe;margin-top:6px;display:block}#dev-sandbox input::placeholder{color:#b0c9e8}";document.head.appendChild(style);
 const panel=document.createElement("aside");panel.id="dev-sandbox";panel.innerHTML='<header><strong>Developer Testing Sandbox</strong><button id="sandbox-close" aria-label="Close testing sandbox">×</button></header><section><label><input id="sandbox-gps" type="checkbox"> Enable simulated GPS</label><div class="sandbox-grid"><button id="sandbox-target">At Target Shop (0m)</button><button id="sandbox-outside">Out of Bounds (350m)</button></div><div class="sandbox-grid" style="margin-top:7px"><button id="sandbox-boundary">Near Boundary (180m)</button><button id="sandbox-clear">Clear Override</button></div><small>Lat <span id="sandbox-lat">-</span> / Lon <span id="sandbox-lon">-</span></small></section><section><div class="demo-note">Sample geofence override</div><div class="sandbox-inputs"><input id="sandbox-lat-input" type="number" step="0.000001" placeholder="Latitude" value="13.0827" /><input id="sandbox-lon-input" type="number" step="0.000001" placeholder="Longitude" value="80.2707" /></div><button id="sandbox-apply-demo" style="margin-top:8px;width:100%">Apply Sample Geo</button></section><section><label for="sandbox-token">QR test token</label><select id="sandbox-token" style="width:100%;margin-top:7px"><option value="">Valid HMAC token</option><option value="">Tampered HMAC token</option></select><button id="sandbox-inject" style="margin-top:8px">Inject Test Token</button></section><section><button id="sandbox-offline">Simulate Offline</button> <button id="sandbox-sync">Sync Queue</button></section><section><button id="sandbox-seed">Seed Test Data</button><div id="sandbox-result" style="margin-top:8px;color:#bae6fd"></div></section>';
 document.body.appendChild(panel);document.getElementById("sandbox-close").onclick=()=>panel.remove();
 document.getElementById("sandbox-gps").onchange=e=>{if(!e.target.checked){window.lmSandboxGps=null;window.demoGeoOverride=null;updateConnectionStatus("GPS simulation disabled")}else setSandboxGps(Number(document.getElementById("sandbox-lat-input").value||13.0827),Number(document.getElementById("sandbox-lon-input").value||80.2707))};
 document.getElementById("sandbox-target").onclick=()=>{document.getElementById("sandbox-gps").checked=true;setSandboxGps(13.0827,80.2707)};
 document.getElementById("sandbox-boundary").onclick=()=>{document.getElementById("sandbox-gps").checked=true;setSandboxGps(13.0842,80.2721)};
 document.getElementById("sandbox-outside").onclick=()=>{document.getElementById("sandbox-gps").checked=true;setSandboxGps(13.08585,80.2707)};
 document.getElementById("sandbox-clear").onclick=()=>{window.lmSandboxGps=null;window.demoGeoOverride=null;document.getElementById("sandbox-gps").checked=false;updateConnectionStatus("Demo GPS cleared")};
 document.getElementById("sandbox-apply-demo").onclick=()=>{const lat=Number(document.getElementById("sandbox-lat-input").value); const lon=Number(document.getElementById("sandbox-lon-input").value); document.getElementById("sandbox-gps").checked=true; const point = applyDemoGeo(lat, lon, "Manual demo GPS"); if (point) { document.getElementById("sandbox-lat").textContent=point.latitude.toFixed(6); document.getElementById("sandbox-lon").textContent=point.longitude.toFixed(6); } };
 document.getElementById("sandbox-inject").onclick=injectSandboxToken;document.getElementById("sandbox-seed").onclick=seedSandboxData;document.getElementById("sandbox-sync").onclick=syncInspectionQueue;
 document.getElementById("sandbox-offline").onclick=e=>{window.lmSandboxOffline=!window.lmSandboxOffline;e.target.textContent=window.lmSandboxOffline?"Simulate Online":"Simulate Offline";updateConnectionStatus()};loadSandboxTokens();
}
function renderAuthState(){
 const user=currentUser();if(!user||document.getElementById("lm-auth-state"))return;
 const badge=document.createElement("div");badge.id="lm-auth-state";badge.style="position:fixed;right:18px;top:14px;z-index:110;display:flex;align-items:center;gap:8px;background:#0f2942;color:white;padding:7px 10px;border-radius:999px;font:600 12px system-ui,sans-serif;box-shadow:0 4px 18px #00142855";badge.innerHTML=`<span style="width:25px;height:25px;border-radius:50%;display:grid;place-items:center;background:#fd651e">${(user.name||user.email||"U")[0].toUpperCase()}</span><span>${user.name||user.email}<small style="display:block;color:#b0c9e8">${user.auth_role||user.role}</small></span><button id="lm-logout" style="border:0;border-radius:5px;padding:4px 7px;cursor:pointer">Logout</button>`;document.body.appendChild(badge);document.getElementById("lm-logout").onclick=logout;
}
function guardProtectedPages(){
 const page=location.pathname.split("/").pop().replace(/\.html$/i,"");
 if(["inspector-dashboard","verify-submission","merchant","lmo","admin"].includes(page)&&!token()){location.replace("login.html")}
}
function initOperationsWorkspace(){
 if(location.pathname.split("/").pop()!=="admin.html")return;
 const nav=[...document.querySelectorAll("a")].filter(a=>["Dashboard","Application Queue","Inspector Allotment","Registered Instruments","LMO Directory"].some(label=>a.textContent.trim().replace(/\s+/g," ").startsWith(label)));
 if(!nav.length)return;
 const root=document.querySelector("main > div");if(!root)return;
 const panel=document.createElement("section");panel.id="operations-workspace";panel.style="margin:0 0 24px;padding:20px;background:#fff;border:1px solid #c3c6ce;border-radius:10px;box-shadow:0 8px 24px #0f29421a";root.insertBefore(panel,root.firstChild);
 const titles={dashboard:"Dashboard",queue:"Application Queue",allotment:"Inspector Allotment",instruments:"Registered Instruments",officers:"LMO Directory"};
 let activeTab="dashboard";
 const esc=value=>String(value??"").replace(/[&<>\"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[char]));
 const setActive=tab=>{activeTab=tab;nav.forEach(link=>{const selected=link.dataset.operationTab===tab;link.dataset.operationTab=link.dataset.operationTab||({Dashboard:"dashboard","Application Queue":"queue","Inspector Allotment":"allotment","Registered Instruments":"instruments","LMO Directory":"officers"}[Object.keys({Dashboard:1,"Application Queue":1,"Inspector Allotment":1,"Registered Instruments":1,"LMO Directory":1}).find(label=>link.textContent.trim().replace(/\s+/g," ").startsWith(label))]||"");link.classList.toggle("bg-primary-container",selected);link.classList.toggle("text-on-primary",selected);link.classList.toggle("text-on-surface-variant",!selected);link.href="#operations-workspace"});loadTab()};
 const message=html=>{panel.innerHTML=`<div style="font:14px Public Sans,sans-serif;color:#43474d">${html}</div>`};
 async function loadTab(){
  const heading=`<div style="display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap;margin-bottom:16px"><div><div style="font:700 11px Public Sans,sans-serif;letter-spacing:.1em;text-transform:uppercase;color:#74777e">Operations Console</div><h2 style="margin:4px 0 0;font:700 24px Public Sans,sans-serif;color:#001428">${titles[activeTab]}</h2></div><span style="padding:6px 10px;background:#e5eeff;border-radius:999px;color:#0f2942;font:700 12px Public Sans,sans-serif">Live API data</span></div>`;
  try{
   if(activeTab==="dashboard"){const d=await api("/v1/dashboard/stats");panel.innerHTML=heading+`<div style="display:grid;grid-template-columns:repeat(4,minmax(140px,1fr));gap:12px">${[["Verified instruments",d.total_verified_instruments],["Pending inspections",d.pending_inspections],["Active officers",d.active_officers],["Geo-fence breaches",d.geo_fence_breach_alerts]].map(([label,value])=>`<div style="padding:16px;background:#eff4ff;border-left:4px solid #fd651e;border-radius:6px"><div style="font:12px Public Sans,sans-serif;color:#596b7e">${label}</div><strong style="display:block;margin-top:8px;font:700 28px Public Sans,sans-serif;color:#001428">${value}</strong></div>`).join("")}</div>`}
   if(activeTab==="queue"){const rows=await api("/v1/applications/queue");panel.innerHTML=heading+`<div style="display:flex;gap:8px;margin-bottom:12px"><select id="queue-filter" style="padding:8px;border:1px solid #c3c6ce;border-radius:4px"><option value="">All statuses</option><option>PENDING</option><option>APPROVED</option><option>REJECTED</option></select></div><div id="queue-table"></div>`;const renderQueue=items=>{document.getElementById("queue-table").innerHTML=`<table style="width:100%;border-collapse:collapse;font:13px Public Sans,sans-serif"><thead><tr style="text-align:left;background:#eff4ff"><th style="padding:10px">Trader</th><th>Instrument</th><th>District</th><th>Status</th><th>Action</th></tr></thead><tbody>${items.map(row=>`<tr><td style="padding:10px;border-bottom:1px solid #e5eeff">${esc(row.trader)}</td><td>${esc(row.instrument)}</td><td>${esc(row.district)}</td><td>${esc(row.status)}</td><td><button data-review="${esc(row.id)}" style="padding:6px 10px;background:#0f2942;color:white;border:0;border-radius:4px">Review</button></td></tr>`).join("")||'<tr><td colspan="5" style="padding:14px">No applications found.</td></tr>'}</tbody></table>`;document.querySelectorAll("[data-review]").forEach(button=>button.onclick=()=>alert(`Application ${button.dataset.review} selected for review.`))};renderQueue(rows);document.getElementById("queue-filter").onchange=async event=>renderQueue(await api(`/v1/applications/queue?status=${event.target.value}`))}
   if(activeTab==="allotment"){const data=await api("/v1/inspectors/allotment");panel.innerHTML=heading+`<div style="display:grid;grid-template-columns:1fr 1fr;gap:16px"><div><h3 style="font:700 16px Public Sans,sans-serif">Pending queues</h3>${data.pending.map(row=>`<div data-application="${esc(row.id)}" style="padding:12px;border:1px solid #c3c6ce;border-radius:6px;margin:8px 0"><strong>${esc(row.instrument)}</strong><div style="font-size:12px;color:#596b7e">${esc(row.district)} · ${esc(row.status)}</div></div>`).join("")}</div><div><h3 style="font:700 16px Public Sans,sans-serif">Assign to officer</h3><select id="allot-application" style="width:100%;padding:9px;margin:8px 0"><option value="">Select application</option>${data.pending.map(row=>`<option value="${esc(row.id)}">${esc(row.instrument)} · ${esc(row.district)}</option>`).join("")}</select><select id="allot-officer" style="width:100%;padding:9px;margin:8px 0"><option value="">Select officer</option>${data.officers.map(row=>`<option value="${esc(row.id)}">${esc(row.name)} · ${esc(row.district)}</option>`).join("")}</select><button id="allot-submit" style="padding:9px 12px;background:#0f2942;color:#fff;border:0;border-radius:4px">Assign inspection</button><div id="allot-result" style="margin-top:10px"></div></div></div>`;document.getElementById("allot-submit").onclick=async()=>{try{const result=await api("/v1/inspectors/allotment",{method:"POST",body:{application_id:document.getElementById("allot-application").value,officer_id:document.getElementById("allot-officer").value}});document.getElementById("allot-result").textContent=`Assigned: ${result.status}`;loadTab()}catch(error){document.getElementById("allot-result").textContent=error.message}}}
   if(activeTab==="instruments"){panel.innerHTML=heading+`<input id="instrument-search" placeholder="Search serial or model" style="width:100%;padding:10px;border:1px solid #c3c6ce;border-radius:4px;margin-bottom:12px"><div id="instrument-table"></div>`;const render=items=>{document.getElementById("instrument-table").innerHTML=`<table style="width:100%;border-collapse:collapse;font:13px Public Sans,sans-serif"><thead><tr style="text-align:left;background:#eff4ff"><th style="padding:10px">Serial</th><th>Model</th><th>Capacity</th><th>District</th><th>Calibration</th><th>QR</th></tr></thead><tbody>${items.map(row=>`<tr><td style="padding:10px;border-bottom:1px solid #e5eeff">${esc(row.serial_number)}</td><td>${esc(row.model)}</td><td>${esc(row.capacity)}</td><td>${esc(row.district)}</td><td>${esc(row.last_calibration)}</td><td>${esc(row.qr_status)}</td></tr>`).join("")}</tbody></table>`};render(await api("/v1/instruments"));document.getElementById("instrument-search").oninput=async event=>render(await api(`/v1/instruments?search=${encodeURIComponent(event.target.value)}`))}
   if(activeTab==="officers"){const rows=await api("/v1/officers");panel.innerHTML=heading+`<table style="width:100%;border-collapse:collapse;font:13px Public Sans,sans-serif"><thead><tr style="text-align:left;background:#eff4ff"><th style="padding:10px">Officer</th><th>Designation</th><th>Contact</th><th>District</th><th>Field status</th></tr></thead><tbody>${rows.map(row=>`<tr><td style="padding:10px;border-bottom:1px solid #e5eeff">${esc(row.name)}</td><td>${esc(row.designation)}</td><td>${esc(row.phone)}</td><td>${esc(row.district)}</td><td>${esc(row.field_status)}</td></tr>`).join("")}</tbody></table>`}
  }catch(error){message(heading+`<div style="padding:12px;background:#fff1f0;color:#b42318;border-radius:6px">${esc(error.message)}. Please sign in with an administrator account.</div>`)}
 }
 nav.forEach(link=>{const key=link.textContent.trim().replace(/\s+/g," ");link.dataset.operationTab={Dashboard:"dashboard","Application Queue":"queue","Inspector Allotment":"allotment","Registered Instruments":"instruments","LMO Directory":"officers"}[key]||({Dashboard:"dashboard","Application Queue":"queue","Inspector Allotment":"allotment","Registered Instruments":"instruments","LMO Directory":"officers"}[Object.keys({Dashboard:1,"Application Queue":1,"Inspector Allotment":1,"Registered Instruments":1,"LMO Directory":1}).find(label=>key.startsWith(label))]);link.onclick=event=>{event.preventDefault();setActive(link.dataset.operationTab)}});new MutationObserver(()=>{document.querySelectorAll("[data-review]").forEach(review=>{if(review.parentElement.querySelector("[data-assign]"))return;const assign=document.createElement("button");assign.dataset.assign=review.dataset.review;assign.textContent="Assign LMO Inspector";assign.style="padding:6px 10px;margin-left:4px;background:#fd651e;color:white;border:0;border-radius:4px";assign.onclick=()=>setActive("allotment");review.after(assign)})}).observe(panel,{childList:true,subtree:true});setActive("dashboard");
}
document.addEventListener("DOMContentLoaded",()=>{guardProtectedPages();renderAuthState();initOperationsWorkspace();const toggle=document.createElement("button");toggle.type="button";toggle.textContent="DEV";toggle.title="Open Developer Testing Sandbox";toggle.style="position:fixed;right:18px;bottom:18px;z-index:121;background:#0f2942;color:#fff;border:1px solid #38bdf8;border-radius:999px;padding:8px 12px;font:700 11px system-ui,sans-serif;cursor:pointer";toggle.onclick=renderSandbox;document.body.appendChild(toggle)});
